### ISSUE TITLE
Move documentation to Github

### ISSUE THREAD

**Issue by farshidtz** [linksmart/data-processing-agent#73]
Move component documentation from [confluence](https://docs.linksmart.eu/display/LA) to github wiki.

**Comment by farshidtz** [comment]
@dasEnder 
Do you have the API docs available anywhere?
https://docs.linksmart.eu/display/LA/Open+API+Docs

**Comment by dasEnder** [comment]
Here https://github.com/linksmart/data-processing-agent/blob/master/api-docs.json 

The OpenApi file it's autogenerated by the CI

**Comment by dschowta** [comment]
Migration is done. there are some broken links. This is being tracked in #74
